version: "3"
services:
  logio:
    build:
     context: ./build
    privileged: true
    restart: always
    environment:
      - AUTH=enable
      - AUTH_LOGIN=admin10
      - AUTH_PASS=qwerty13q
    volumes:
        - ./logio_scan_files/conf:/home/logio/conf
        - ./logio_scan_files/pods:/home/logio/pods 
        - ./logio_scan_files/logs:/home/logio/logs
        - ./logio_scan_files/trigger:/home/logio/trigger
    ports:
        - "28778:28778"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 256M
