version: "3.7"
services:
    build: ./build
    privileged: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        # reservations:
        #   cpus: '0.25'
        #   memory: 128M
    environment:
      - AUTH=enable
      - AUTH_LOGIN=admin10
      - AUTH_PASS=qwerty13q
    ports:
        - "28778:28778"
    volumes:
        - ./logio_scan_files/conf:/home/logio/conf
        - ./logio_scan_files/pods:/home/logio/pods 
        - ./logio_scan_files/logs:/home/logio/logs
        - ./logio_scan_files/trigger:/home/logio/trigger